from typing import *
from dataclasses import dataclass
from pathlib import Path
from abc import ABC, abstractmethod

FilePath = Path
FolderPath = Path


@dataclass
class ConversionOutcome():
    """
    A class representing the outcome of a file conversion operation.

    Attributes:
    - input_file (FilePath): The input file for the conversion.
    - output_files (List[FilePath]): The output files generated by the conversion.
    - warning_messages (List[str]): Any warning messages generated during the conversion.
    
    - skipped (bool): Indicates whether the conversion was skipped. Default is False.
    - successful (bool): Indicates whether the conversion was successful. Default is True.
    - error_message (str): Contains any error message generated during the conversion. Default is an empty string.
    - halt (bool): Indicates whether the conversion should be halted. Default is False.
    """
    input_file: FilePath
    output_files: List[FilePath]
    warning_messages: List[str]
    
    skipped: bool = False
    successful: bool = True
    error_message: str = ""
    halt: bool = False


class ConversionFunction(ABC):
    """
    An abstract base class representing a conversion function.

    Attributes:
    - is_batchable (ClassVar[bool]): Indicates whether the conversion function can handle batch processing.

    Methods:
    - __call__(self, *args, **kwargs) -> List[ConversionOutcome]: An abstract method that should be implemented by subclasses to perform the conversion operation.
    """
    is_batchable: ClassVar[bool]

    @abstractmethod
    def __call__(self, *args, **kwargs) -> List[ConversionOutcome]:...


class SingleFileConversionFunction(ConversionFunction):
    """
    An abstract class representing a single-file conversion function.

    Inherits from ConversionFunction.

    Attributes:
    - is_batchable (ClassVar[bool]): Indicates that this conversion function can handle single-file processing.

    Methods:
    - __call__(self, input_file: FilePath, output_folder: FolderPath, overwrite: bool = True) -> List[ConversionOutcome]: An abstract method that should be implemented by subclasses to perform the single-file conversion operation.
    """
    is_batchable: ClassVar[bool] = False

    @abstractmethod
    def __call__(self, input_file: FilePath, output_folder: FolderPath, overwrite: bool = True) -> List[ConversionOutcome]: ...
        

class BatchConversionFunction(ConversionFunction):
    """
    An abstract class representing a batch conversion function.

    Inherits from ConversionFunction.

    Attributes:
    - is_batchable (ClassVar[bool]): Indicates that this conversion function can handle batch processing.

    Methods:
    - __call__(self, input_path: FilePath | FolderPath, output_folder: FolderPath, do_batch: bool = True, overwrite: bool = True) -> List[ConversionOutcome]: A method that handles both single-file and batch processing based on the `do_batch` parameter.
    
    Concretely, the __call__ method is overloaded so that the type checker expects a FilePath for a True `do_batch` parameter and a FolderPath for a False `do_batch` parameter.
    """
    is_batchable: ClassVar[bool] = True
    
    @overload
    def __call__(self, input_path: FilePath, output_folder: FolderPath, do_batch: Literal[False], overwrite: bool = True) -> List[ConversionOutcome]: ...
    
    @overload
    def __call__(self, input_path: FolderPath, output_folder: FolderPath, do_batch: Literal[True], overwrite: bool = True) -> List[ConversionOutcome]: ...
    
    @abstractmethod
    def __call__(self, input_path: FilePath | FolderPath, output_folder: FolderPath, do_batch: bool = True, overwrite: bool = True) -> List[ConversionOutcome]: ...

_ConversionFunction = Union[SingleFileConversionFunction, BatchConversionFunction]